# Generated by Django 4.0.3 on 2022-03-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbyapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='diypost',
        ),
        migrations.AddField(
            model_name='like',
            name='diypost',
            field=models.ManyToManyField(related_name='likes', to='dbyapi.post'),
        ),
        migrations.RemoveField(
            model_name='like',
            name='liker',
        ),
        migrations.AddField(
            model_name='like',
            name='liker',
            field=models.ManyToManyField(related_name='likes', to='dbyapi.diyuser'),
        ),
    ]
