# Generated by Django 4.0.3 on 2022-03-12 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbyapi', '0002_remove_like_diypost_like_diypost_remove_like_liker_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='diyuser',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='diyuser',
        ),
    ]
