# Generated by Django 4.0.3 on 2022-03-12 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbyapi', '0003_rename_user_comment_diyuser_rename_user_post_diyuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='follower',
        ),
        migrations.AddField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='followed_by', to='dbyapi.diyuser'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='follow',
            name='following',
        ),
        migrations.AddField(
            model_name='follow',
            name='following',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='dbyapi.diyuser'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='like',
            name='diypost',
        ),
        migrations.AddField(
            model_name='like',
            name='diypost',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='dbyapi.post'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='like',
            name='liker',
        ),
        migrations.AddField(
            model_name='like',
            name='liker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='dbyapi.diyuser'),
            preserve_default=False,
        ),
    ]
