# Generated by Django 4.0.3 on 2022-03-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbyapi', '0007_diyuser_following_delete_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='diyuser',
            name='likes',
            field=models.ManyToManyField(related_name='liked_post', to='dbyapi.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='liked_by', to='dbyapi.diyuser'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
