# Generated by Django 4.0.3 on 2022-03-17 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbyapi', '0008_diyuser_likes_post_likes_delete_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_diyuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_by', to='dbyapi.post')),
                ('to_diyuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to='dbyapi.post')),
            ],
        ),
    ]
