# Generated by Django 4.0.3 on 2022-03-18 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbyapi', '0009_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diyuser',
            name='following',
        ),
        migrations.AddField(
            model_name='diyuser',
            name='following',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='followed_by', to='dbyapi.following'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='diyuser',
            name='likes',
        ),
        migrations.AlterField(
            model_name='following',
            name='from_diyuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_by', to='dbyapi.diyuser'),
        ),
        migrations.AlterField(
            model_name='following',
            name='to_diyuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to='dbyapi.diyuser'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diypost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_post', to='dbyapi.post')),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to='dbyapi.diyuser')),
            ],
        ),
        migrations.AddField(
            model_name='diyuser',
            name='likes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='liked_post', to='dbyapi.like'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='dbyapi.like'),
            preserve_default=False,
        ),
    ]
