# Generated by Django 4.0.3 on 2022-03-19 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbyapi', '0012_remove_diyuser_following_remove_diyuser_likes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='dat',
        ),
    ]
