# Generated by Django 4.0.3 on 2022-03-19 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbyapi', '0013_rename_date_post_dat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dat',
            new_name='date',
        ),
    ]
