# Generated by Django 4.0.3 on 2022-03-19 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbyapi', '0014_rename_dat_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='from_diyuser',
        ),
        migrations.AddField(
            model_name='following',
            name='from_diyuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='followed_by', to='dbyapi.diyuser'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='following',
            name='to_diyuser',
        ),
        migrations.AddField(
            model_name='following',
            name='to_diyuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='following', to='dbyapi.diyuser'),
            preserve_default=False,
        ),
    ]
