# Generated by Django 4.0.3 on 2022-03-19 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbyapi', '0015_remove_following_from_diyuser_following_from_diyuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diyuser',
            name='follows',
        ),
    ]
